---
title: "EDLD 651 Final Project"
format: html
execute: 
  echo: false
editor: visual
---

```{r}
#install.packages("labelled")
#install.packages("kableExtra")
library(tidyverse)
library(here)
library(rio)
library(knitr)
library(labelled)
library(RColorBrewer)
library(kableExtra)
library(ggtext)

df<- import(here("Data/36498-6002-Data.rda"))%>% 
  select(R06_YC9050, R06_YC1124, R06_YC9022, R06_YC1022, R06R_Y_AGECAT2,R06R_Y_SEX, R06R_Y_HISP, R06R_Y_RACECAT3, R06R_Y_PM0130) %>% 
  rename(harmful=R06_YC9050, 
         addict=R06_YC1124, 
         smoker=R06_YC9022, 
         num_cigs=R06_YC1022,
         age=R06R_Y_AGECAT2,
         sex=R06R_Y_SEX, 
         hisp=R06R_Y_HISP, 
         race=R06R_Y_RACECAT3, 
         ses=R06R_Y_PM0130)
  
  # mutate(harmful= as.numeric(harmful), addict=as.numeric(addict), age=as.numeric(age)) #COMMENTED OUT BECAUSE THESE AREN'T CONTINUOUS ANYWAY, NOT SURE IF NEED THEM AS NUMERIC 

# df %>% 
#   ggplot(aes(x=addict, fill=harmful))+
#   geom_bar()

# df %>% 
  # ggplot(aes(x=num_cigs, fill=smoker))+
  # geom_bar()
#MADE THESE JUST TO DOUBLE CHECK THAT THE VARIABLES LOOK RIGHT 
```

```{r}

#| label: cleaning

# Didn't think the data needed pivoting
# Cleaned factor labels
# Made a subset of only those who answered affirmatively or negatively whether they identify as a smoker

levels(df$harmful) <- c("1","2","3","4","5")

df <- df %>% 
  mutate(harmful = factor(harmful,
                          levels = c("1","2","3","4","5"),
                          labels = c("Not at all harmful",
                                     "Slightly harmful",
                                     "Somewhat harmful",
                                     "Very harmful",
                                     "Extremely harmful")))

levels(df$addict) <- c("1","2","3","4","5")

df <- df %>% 
  mutate(addict = factor(addict,
                          levels = c("1","2","3","4","5"),
                          labels = c("Very unlikely",
                                     "Somewhat unlikely",
                                     "Neither likely nor unlikely",
                                     "Somewhat likely",
                                     "Very likely")))

levels(df$smoker) <- c("1","2")

df <- df %>% 
  mutate(smoker = factor(smoker, levels = c("1","2"),
                         labels = c("Yes","No")))

levels(df$age) <- c("1","2")

df <- df %>% 
  mutate(age = factor(age, levels = c("1","2"),
                         labels = c("12-14","15-17")))

levels(df$sex) <- c("1","2")

df <- df %>% 
  mutate(sex = factor(sex, levels = c("1","2"),
                         labels = c("Male","Female")))

levels(df$hisp) <- c("1","2")

df <- df %>% 
  mutate(hisp = factor(hisp, levels = c("1","2"),
                         labels = c("Hispanic","Not Hispanic")))

levels(df$race) <- c("1","2","3")

df <- df %>% 
  mutate(race = factor(race, levels = c("1","2","3"),
                         labels = c("White alone","Black alone","Other")))

levels(df$ses) <- c("1","2","3","4","5")

df <- df %>% 
  mutate(ses = factor(ses,
                          levels = c("1","2","3","4","5"),
                          labels = c("Less than $10,000",
                                     "$10,000 to $24,999",
                                     "$25,000 to $49,999",
                                     "$50,000 to $99,999",
                                     "$100,000 or more")))

df_smokers <- df %>% 
  filter(smoker != "NA")
```

```{r}

#| label: tables

#demographics 
demographic_table <- df %>% 
  summarise(
    total = n(),
    Male = sum(sex == "Male", na.rm = TRUE),
    Female = sum(sex == "Female", na.rm = TRUE),
    Age_12_14 = sum(age == "12-14", na.rm = TRUE),
    Age_15_17 = sum(age == "15-17", na.rm = TRUE),
    Hispanic = sum(hisp == "Hispanic", na.rm = TRUE),
    Not_Hispanic = sum(hisp == "Not Hispanic", na.rm = TRUE),
    White = sum(race == "White alone", na.rm = TRUE),
    Black = sum(race == "Black alone", na.rm = TRUE),
    Other = sum(race == "Other", na.rm = TRUE)) %>% 
  pivot_longer(cols = -total, names_to = "Demographic", values_to = "Count") %>% 
  mutate(Percentage = (Count / total) * 100)
demographic_table

plot_1 <- ggplot(demographic_table, aes(x = Demographic, y = Percentage, fill = Demographic)) +
  geom_bar(stat = "identity", show.legend = FALSE) +
  coord_flip() +  
  theme_minimal() +
  labs(title = "Demographic Distribution", x = "Demographic Group", y = "Percentage") +
  scale_fill_brewer(palette = "Set3") +  
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
plot_1

demographic_table_cleaned <- demographic_table %>%
  select(-total) %>%
  mutate(
    Percentage = round(Percentage, 2), 
    Demographic = case_when(
      Demographic == "Age_12_14" ~ "Ages 12-14",
      Demographic == "Age_15_17" ~ "Ages 15-17",
      Demographic == "Male" ~ "Male",
      Demographic == "Female" ~ "Female",
      Demographic == "Hispanic" ~ "Hispanic",
      Demographic == "Not_Hispanic" ~ "Not Hispanic",
      Demographic == "White" ~ "White",
      Demographic == "Black" ~ "Black",
      Demographic == "Other" ~ "Other",
      TRUE ~ Demographic))

kable_table_total <- demographic_table_cleaned %>%
  kbl(caption = "Demographic Distribution of Participants", align = "c") %>%
  kable_styling(
    full_width = FALSE,
    bootstrap_options = c("striped", "hover", "condensed"))
kable_table_total

smoker_demographic_table <- df_smokers %>% 
  summarise(
    total = n(),
    Male = sum(sex == "Male", na.rm = TRUE),
    Female = sum(sex == "Female", na.rm = TRUE),
    Age_12_14 = sum(age == "12-14", na.rm = TRUE),
    Age_15_17 = sum(age == "15-17", na.rm = TRUE),
    Hispanic = sum(hisp == "Hispanic", na.rm = TRUE),
    Not_Hispanic = sum(hisp == "Not Hispanic", na.rm = TRUE),
    White = sum(race == "White alone", na.rm = TRUE),
    Black = sum(race == "Black alone", na.rm = TRUE),
    Other = sum(race == "Other", na.rm = TRUE)) %>% 
  pivot_longer(cols = -total, names_to = "Demographic", values_to = "Count") %>% 
  mutate(Percentage = (Count / total) * 100)
smoker_demographic_table

smoker_demographic_table_cleaned <- smoker_demographic_table %>%
  select(-total) %>%
  mutate(Percentage = round(Percentage, 2),
      Demographic = case_when(
      Demographic == "Age_12_14" ~ "Ages 12-14",
      Demographic == "Age_15_17" ~ "Ages 15-17",
      Demographic == "Male" ~ "Male",
      Demographic == "Female" ~ "Female",
      Demographic == "Hispanic" ~ "Hispanic",
      Demographic == "Not_Hispanic" ~ "Not Hispanic",
      Demographic == "White" ~ "White",
      Demographic == "Black" ~ "Black",
      Demographic == "Other" ~ "Other",
      TRUE ~ Demographic))
kable_table_smokers <- smoker_demographic_table_cleaned %>%
  kbl(caption = "Smoker Demographic Distribution", align = "c") %>%
  kable_styling(
    full_width = FALSE,
    bootstrap_options = c("striped", "hover", "condensed"))
kable_table_smokers

plot_2 <- ggplot(smoker_demographic_table, aes(x = Demographic, y = Percentage, fill = Demographic)) +
  geom_bar(stat = "identity", show.legend = FALSE) +
  coord_flip() +  
  theme_minimal() +
  labs(title = "Smoker Demographic Distribution", x = "Demographic Group", y = "Percentage") +
  scale_fill_brewer(palette = "Set3") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
plot_2

#prob table for perception 
table_harmful <- df %>% 
  group_by(harmful) %>% 
  summarise(count = n()) %>% 
  mutate(prop = count / sum(count)) 
table_harmful

table_harmful_smokers <- df_smokers %>% 
  group_by(harmful) %>% 
  summarise(count = n()) %>% 
  mutate(prop = count / sum(count)) 
table_harmful_smokers


#prob table for perception by age
table_harmful_by_age <- df %>% 
  group_by(age, harmful) %>% 
  summarise(count = n(), .groups = "drop") %>% 
  mutate(prop = count / sum(count))
table_harmful_by_age

table_harmful_by_age_smokers <- df_smokers %>% 
  group_by(age, harmful) %>% 
  summarise(count = n(), .groups = "drop") %>% 
  mutate(prop = count / sum(count))
table_harmful_by_age_smokers

#smoker status by age
#not sure about this one, doesn't change if I use df_smokers / remove filter line of code
table_smoker_age <- df %>% 
  filter(!is.na(smoker)) %>% 
  count(smoker, age) %>% 
  pivot_wider(names_from = age, values_from = n, values_fill = 0)
table_smoker_age

## I think this table is correct. There are 370 obs in the smoker filter, which is not everyone who identified as a smoker but rather those who answered the question, yes OR no. The smoker demographic table is the demographics of everyone who answered; this table shows what the actual distribution of those answers was
```

```{r}
#| label: visuals

# df_smokers %>%
#   ggplot(aes(x=num_cigs)) +
#   geom_histogram(binwidth = 1) +
#   theme_minimal()


# Smoker identity by age 
#Iteration 1.a
df_smokers %>%
  group_by(smoker) %>%
  summarise(mean_cigs = round(mean(num_cigs, na.rm = T),2)) %>%
  ggplot(aes(x=smoker,y=mean_cigs,fill=smoker)) +
  geom_col() 

#Iteration 2.a 
df_smokers %>%
  group_by(smoker) %>%
  summarise(mean_cigs = round(mean(num_cigs, na.rm = T),2)) %>%
  ggplot(aes(x=smoker,y=mean_cigs,fill=smoker)) +
  geom_col() +
  theme_minimal()+
  theme(text = element_text(size = 24))+
  labs(x="Identifies as Smoker", y="Number of Cigarettes Smoked in Past 30 Days", fill="Smoker")

#Iteration 3.a
df_smokers %>%
  group_by(age, smoker) %>% 
  summarise(mean_cigs = round(mean(num_cigs, na.rm = TRUE), 2)) %>%  
  ggplot(aes(x = age, y = mean_cigs, fill = smoker)) +
  geom_col(position = "dodge") +  
   geom_text(aes(label = mean_cigs), 
            position = position_dodge(width = 0.9), 
            vjust = -0.5, size = 3) +
  theme_minimal() +
  labs(
    x = "Age Group",
    y = "Average Number of Cigarettes Smoked in Past 30 Days",
    fill = "Smoker \n Status",
    title = "Cigarette Consumption by Age Group and Smoker Status", 
    caption = 'Source: Population Assessment of Tobacco and Health,
    “DS6002 Wave 6: Youth / Parent Questionnaire Data” ') +
 scale_fill_brewer(palette="Dark2")

# Final iteration 
cons_age <-df_smokers %>%
  group_by(age, smoker) %>% 
  summarise(mean_cigs = round(mean(num_cigs, na.rm = TRUE), 2)) %>%  
  ggplot(aes(x = age, y = mean_cigs, fill = smoker)) +
  geom_col(position = "dodge") +  
   geom_text(aes(label = mean_cigs), 
            position = position_dodge(width = 0.9), 
            vjust = -0.5, size = 3) +
  labs(
    x = "Age Group",
    y = "Average Number of Cigarettes Smoked in Past 30 Days",
    fill = "Smoker \n Status",
    title = "Cigarette Consumption by Age Group and Smoker Status", 
    subtitle = 'Non smokers age 12-14 average 1 cigarette per month, while non-smokers age 15-17 average 2.45 cigarettes per month',
    caption = 'Source: Population Assessment of Tobacco and Health,
    “DS6002 Wave 6: Youth / Parent Questionnaire Data” ') +
 scale_fill_brewer(palette="Dark2")  +
    theme(plot.title= element_markdown(margin = margin(b=5),hjust=0, size = 16, face ='bold'),
        plot.subtitle = element_markdown(margin= margin (b= 5), hjust= 0, size= 12, face ='italic'),
    panel.background = element_rect(fill='white',colour='white'),
    axis.ticks= element_blank(),
    panel.grid.major.y = element_line(color      = "grey80", 
                                              linewidth  = 0.5, 
                                              linetype   = "dashed"),
    plot.caption= element_text(hjust = 0.01, 
                               size = 9,
                               margin=margin(t=0)))



# Perceptions of cigarette harm by income level
#Iteration 1.b 
df %>%
ggplot(aes(x=harmful, fill=harmful))+
geom_bar()


#Iteration 2.b 
df %>%
ggplot(aes(x=harmful, fill=harmful))+
geom_bar()+
theme_minimal()+
labs(x= "Belief of Cigarette Harmfulness", y="Count", fill="Belief")+
theme(text = element_text(size = 26))

#Iteration 3.b 
df %>%
  ggplot(aes(x = ses, fill = harmful)) +  # x-axis = race, fill = harmful beliefs
  geom_bar(position = "stack") +  # Stacked bar chart
  theme_minimal() +
  labs(
    x = "Income",
    y = "Count",
    fill = "Perceptions of harm",
    title = "Perceptions of cigarette harm by income level", 
    caption = 'Source: Population Assessment of Tobacco and Health “DS6002 Wave 6: Youth / Parent Questionnaire Data” '
  ) +
  scale_fill_brewer(palette = "Dark2")

# 4.b
df %>%
  ggplot(aes(x = ses, fill = harmful)) + 
  geom_bar(position = "stack") +    
  theme_minimal() +
  labs(
    x = "Income",
    y = "Count",
    fill = "Perceptions of harm",
    title = "Perceptions of cigarette harm by income level", 
    subtitle = 'Statement',
    caption = 'Source: Population Assessment of Tobacco and Health \n“DS6002 Wave 6: Youth / Parent Questionnaire Data” '
  ) +
  scale_fill_brewer(palette = "Dark2") + 
    theme(plot.title= element_markdown(margin = margin(b=5),hjust=0, size = 16, face ='bold'),
        plot.subtitle = element_markdown(margin= margin (b= 5), hjust= 0, size= 12, face ='italic'),
    panel.background = element_rect(fill='white',colour='white'),
    axis.ticks= element_blank(),
    panel.grid.major.y = element_line(color      = "grey80", 
                                              linewidth  = 0.5, 
                                              linetype   = "dashed"),
    plot.caption= element_text(hjust = 0.01, 
                               size = 9,
                               margin=margin(t=0)))
    
#Final 
perc_income <- df %>%
  count(ses, harmful) %>% # Count occurrences of each harmful level grouped by ses
  ggplot(aes(x = harmful, y = n, fill = ses)) + 
  geom_col(position = "dodge") +    
  theme_minimal() +
  coord_flip() +
  labs(
    y = "Count",
    title = "Perceptions of cigarette harm by income level", 
    caption = 'Source: Population Assessment of Tobacco and Health \n“DS6002 Wave 6: Youth / Parent Questionnaire Data” ') + 
   guides(fill = guide_legend(title = NULL)) + 
   geom_text(aes(label = n), 
            position = position_dodge(width = 0.9), 
            vjust = .5, hjust= -.3, size = 3.5) +  
  scale_fill_brewer(palette = "Dark2", na.value = "grey") +
    theme(plot.title= element_markdown(margin = margin(b=5),hjust=0, size = 16, face ='bold'),
    panel.background = element_rect(fill='white',colour='white'),
    axis.ticks= element_blank(),
    axis.title.y = element_blank(),
    panel.grid.major.y = element_line(color      = "grey80", 
                                              linewidth  = 0.5, 
                                              linetype   = "dashed"),
    plot.caption= element_text(hjust = 0.01, 
                               size = 9,
                               margin=margin(t=0)))
  

    
#Perceived likelihood of cigarette addiction
#Iteration 1.c
df %>%
  ggplot(aes(x=addict, fill=addict))+
  geom_bar()

#Iteration 2.c
df_smokers %>%
  count(addict) %>%
  mutate(
    percent = n / sum(n) * 100,  
    label_pos = cumsum(percent) - percent / 2) %>%
  ggplot(aes(x = "", y = percent, fill = addict)) +
  geom_bar(stat = "identity", width = 1) + 
  coord_polar("y", start = 0) 

#Final Iteration 
cig_addic <-df_smokers %>%
  count(addict) %>%
  mutate(
    percent = n / sum(n) * 100,  
    label_pos = cumsum(percent) - percent / 2) %>%
  ggplot(aes(x = "", y = percent, fill = addict)) +
  geom_bar(stat = "identity", width = 1) + 
  coord_polar("y", start = 0) +
  geom_text(aes(label = ifelse(percent > 4, paste0(round(percent, 1), "%"), "")),
    position = position_stack(vjust = 0.5),
    size = 5,
    color = "white" ) +
  labs(title = "Perceived likelihood of cigarette addiction",
       subtitle = "Nearly 50% of participants report someone is very likely to become addicted to cigarettes",
    caption = 'Source: Population Assessment of Tobacco and Health,\n“DS6002 Wave 6: Youth / Parent Questionnaire Data” ') +
  theme_void() +
  theme(
    legend.title = element_blank()) + 
   scale_fill_brewer(palette = "Dark2", na.value = "grey")+ 
      theme(plot.title= element_markdown(hjust=0, size = 16, face ='bold'),
        plot.subtitle = element_markdown(margin= margin (b= 5), hjust= 0, size= 12, face ='italic'),
    panel.background = element_rect(fill='white',colour='white'),
    plot.caption= element_text(hjust = 0.01, 
                               size = 9,
                               margin=margin(t=0))) + 
      annotate('text',
             x        = 1.54,
             y        = 1,
             hjust    = .1,
             vjust    = 0,
             label    = '0.8%',
             size     = 5,
             color    = 'black') + 
        annotate('text',
             x        = 1.57,
             y        = 97,
             hjust    = .1,
             vjust    = 0,
             label    = '3.2%',
             size     = 5,
             color    = 'black') + 
    annotate("segment", x = 1.5, y = 98, xend = 1.50, yend=98.2,
         arrow = arrow(type = "closed", length = unit(0.005, "npc")))+ 
      annotate("segment", x = 1.53, y = 2, xend = 1.50, yend=.8,
         arrow = arrow(type = "closed", length = unit(0.005, "npc")))

```

```{r}
#| label: regression models

# harmful as predictor of smoker status

library(modelsummary)

m1 <- glm(smoker~harmful+age+sex+race+ses,
          data = df_smokers,
          family = binomial(link = "logit"))



modelsummary(m1, fmt = 2,
             exponentiate = TRUE,
             statistic = "conf.int",
             stars = TRUE,
             coef_omit = "(Intercept)",
             gof_omit = "AIC|BIC|Log.Lik|RMSE")

m1_coef <- summary(m1)$coefficients

library(janitor)
m1_coef <- m1_coef %>% clean_names()
m1_coef[,1] <- exp(m1_coef[,1])
m1_coef[,1] <- round((m1_coef[,1]),2)
m1_coef[,c(2,3,4)] <- round((m1_coef[,c(2,3,4)]),2)
colnames(m1_coef)[4] <- "p_value"
rownames(m1_coef)[1] <- "Intercept"
rownames(m1_coef)[c(2,3,4,5)] <- c("Slightly Harmful","Somewhat Harmful",
                                "Very Harmful", "Extremely Harmful")
rownames(m1_coef)[c(6,7,8,9)] <- c("Age 15-17","Female","Black",
                                   "Other Racial Identity")
rownames(m1_coef)[c(10,11,12,13)] <- c("$10,000-24,999",
                                       "$25,000-49,999",
                                       "$50,000-99,999",
                                       "Over $100,000")

## TABLE 3 ##
kable(m1_coef)

# no significant predictors; perceived harmfulness of cigs is not associated (pos or neg) w smoker status

# addict as predictor of smoker status

m2 <- glm(smoker~addict+age+sex+race+ses,
          data = df_smokers,
          family = binomial(link = "logit"))

modelsummary(m2, fmt = 2,
             exponentiate = TRUE,
             statistic = "conf.int",
             stars = TRUE,
             coef_omit = "(Intercept)",
             gof_omit = "AIC|BIC|Log.Lik|RMSE")

m2_coef <- summary(m2)$coefficients
m2_coef <- m2_coef %>% clean_names()
m2_coef[,1] <- exp(m2_coef[,1])
m2_coef[,c(1,2,3,4)] <- round((m2_coef[,c(1,2,3,4)]),2)
colnames(m2_coef)[4] <- "p_value"
rownames(m2_coef)[1] <- "Intercept"
rownames(m2_coef)[c(2,3,4,5)] <- c("Somewhat Unlikely",
                                   "Neither Likely nor Unlikely",
                                "Somewhat Likely", "Very Likely")
rownames(m2_coef)[c(6,7,8,9)] <- c("Age 15-17","Female","Black",
                                   "Other Racial Identity")
rownames(m2_coef)[c(10,11,12,13)] <- c("$10,000-24,999",
                                       "$25,000-49,999",
                                       "$50,000-99,999",
                                       "Over $100,000")

## TABLE 4 ##
kable(m2_coef)


# same, no significant predictors...beliefs about likelihood of addiction are not associated w smoker status

# harmful as predictor of num. cigs

m3 <- lm(num_cigs~harmful+age+sex+race+ses,
   data=df_smokers,
   na.action = na.omit)

modelsummary(m3,stars = T, fmt = 2,
             gof_omit = "Adj.|AIC|BIC|RMSE|Log")

m3_coef <- summary(m3)$coefficients
m3_coef <- m3_coef %>% clean_names()
m3_coef[,c(1,2,3,4)] <- round((m3_coef[,c(1,2,3,4)]),2)
colnames(m3_coef)[4] <- "p_value"
rownames(m3_coef)[1] <- "Intercept"
rownames(m3_coef)[c(2,3,4,5)] <- c("Slightly Harmful","Somewhat Harmful",
                                "Very Harmful", "Extremely Harmful")
rownames(m3_coef)[c(6,7,8,9)] <- c("Age 15-17","Female","Black",
                                   "Other Racial Identity")
rownames(m3_coef)[c(10,11,12,13)] <- c("$10,000-24,999",
                                       "$25,000-49,999",
                                       "$50,000-99,999",
                                       "Over $100,000")

## TABLE 5 ##

kable(m3_coef)


# one significant predictor, ON AVG IN THE POPULATION ppl in SES 25-49.999k smoked 8.37 more cigs

# last model, addict as predictor of num. cigs

m4 <- lm(num_cigs~addict+age+sex+race+ses,
   data=df_smokers,
   na.action = na.omit)

modelsummary(m4,stars = T, fmt = 2,
             gof_omit = "Adj.|AIC|BIC|RMSE|Log")

m4_coef <- summary(m4)$coefficients
m4_coef <- m4_coef %>% clean_names()
m4_coef[,c(1,2,3,4)] <- round((m4_coef[,c(1,2,3,4)]),2)
colnames(m4_coef)[4] <- "p_value"
rownames(m4_coef)[1] <- "Intercept"
rownames(m4_coef)[c(2,3,4)] <- c("Neither Likely nor Unlikely",
                                "Somewhat Likely", "Very Likely")
rownames(m4_coef)[c(5,6,7,8)] <- c("Age 15-17","Female","Black",
                                   "Other Racial Identity")
rownames(m4_coef)[c(9,10,11,12)] <- c("$10,000-24,999",
                                       "$25,000-49,999",
                                       "$50,000-99,999",
                                       "Over $100,000")

## TABLE 6 ##

kable(m4_coef)



# intercept (which is "very unlikely to get addicted") had a p < .1; again, ses 25-49.999k was significantly associated w smoking 8.5 more cigs

# modelsummary() creates tables; summary() reports p-values. If someone wants, we can maybe make a vector of coefficients and p-values...or, I wonder whether we could save summary() results as a df...though we'd need to exponentiate m1 and m2 coefficients for log. odds

# just for funzies

m5 <- lm(num_cigs~smoker+age+sex+race+ses,
   data=df_smokers,
   na.action = na.omit)

modelsummary(m5,stars = T, fmt = 2,
             coef_rename = c("smokerNo" = "Non-Smoker",
                             "age15-17" = "Age 15-17",
                             "sexFemale" = "Female",
                             "raceBlack alone" = "Black",
                             "raceOther" = "Other Racial Identity"),
             gof_omit = "Adj.|AIC|BIC|RMSE|Log",
             title = "Associations between Smoker Status,
             Demographic Variables, and Num. of Cigs")

m5_coef <- summary(m5)$coefficients
m5_coef <- m5_coef %>% clean_names()
m5_coef[,c(1,2,3,4)] <- round((m5_coef[,c(1,2,3,4)]),2)
colnames(m5_coef)[4] <- "p_value"
rownames(m5_coef)[1] <- "Intercept"
rownames(m5_coef)[c(2,3,4,5,6)] <- c("Non-Smoker","Age 15-17",
                                     "Female","Black",
                                   "Other Racial Identity")
rownames(m5_coef)[c(7,8,9,10)] <- c("$10,000-24,999",
                                       "$25,000-49,999",
                                       "$50,000-99,999",
                                       "Over $100,000")

## TABLE 7 ##

kable(m5_coef)



# After adjusting for age, sex, race, and SES, on average in the pop., identifying as a non-smoker is significantly (p < .001) associated with consuming 12.5 fewer cigarettes per [unit of time]
```

```{r}

#|label: new-boot-goofing

library(forcats)

df_smokers_dichotomous <- df_smokers %>% 
  mutate(harmful = fct_collapse(harmful,
                                `Not harmful` = c("Not at all harmful",
                                                  "Slightly harmful"),
                                `Somewhat harmful` = "Somewhat harmful",
                                `Harmful`= c("Very harmful",
                                             "Extremely harmful")),
         addict = fct_collapse(addict,
                               `Not likely` = c("Very unlikely",
                                                "Somewhat unlikely"),
                               `Neither likely nor unlikely` = "Neither likely nor unlikely",
                               `Likely` = c("Somewhat likely",
                                            "Very likely")))

m6 <- glm(smoker~harmful+age+sex+race+ses,
          data = df_smokers_dichotomous,
          family = binomial(link = "logit"))

modelsummary(m6, fmt = 2,
             exponentiate = TRUE,
             statistic = "conf.int",
             stars = TRUE,
             coef_omit = "(Intercept)",
             gof_omit = "AIC|BIC|Log.Lik|RMSE")

m7 <- glm(smoker~addict+age+sex+race+ses,
          data = df_smokers_dichotomous,
          family = binomial(link = "logit"))

modelsummary(m7, fmt = 2,
             exponentiate = TRUE,
             statistic = "conf.int",
             stars = TRUE,
             coef_omit = "(Intercept)",
             gof_omit = "AIC|BIC|Log.Lik|RMSE")

m8 <- lm(num_cigs~harmful+age+sex+race+ses,
   data=df_smokers_dichotomous,
   na.action = na.omit)

modelsummary(m8,stars = T, fmt = 2,
             gof_omit = "Adj.|AIC|BIC|RMSE|Log")

m9 <- lm(num_cigs~addict+age+sex+race+ses,
   data=df_smokers_dichotomous,
   na.action = na.omit)

modelsummary(m9,stars = T, fmt = 2,
             gof_omit = "Adj.|AIC|BIC|RMSE|Log")

m10 <- lm(num_cigs~smoker+age+sex+race+ses,
   data=df_smokers_dichotomous,
   na.action = na.omit)

summary(m10)
```
